package org.kxml2.wap.wv;

import com.hiti.Flurry.FlurryLogString;
import com.hiti.sql.offlineadinfo.parser.OfflineADParser;
import com.hiti.ui.collageview.CollageParser;
import com.hiti.ui.edmview.EDMView.EDMViewHandler.ControllerState;
import java.io.IOException;
import javax.jmdns.impl.constants.DNSConstants;
import org.apache.commons.net.nntp.NNTP;
import org.apache.commons.net.pop3.POP3;
import org.ksoap2.SoapEnvelope;
import org.kxml2.wap.WbxmlParser;

public abstract class WV {
    public static final String[] attrStartTable;
    public static final String[] attrValueTable;
    public static final String[] tagTablePage0;
    public static final String[] tagTablePage1;
    public static final String[] tagTablePage2;
    public static final String[] tagTablePage3;
    public static final String[] tagTablePage4;
    public static final String[] tagTablePage5;
    public static final String[] tagTablePage6;
    public static final String[] tagTablePage7;
    public static final String[] tagTablePage8;
    public static final String[] tagTablePage9;
    public static final String[] tagTablePageA;

    public static WbxmlParser createParser() throws IOException {
        WbxmlParser parser = new WbxmlParser();
        parser.setTagTable(0, tagTablePage0);
        parser.setTagTable(1, tagTablePage1);
        parser.setTagTable(2, tagTablePage2);
        parser.setTagTable(3, tagTablePage3);
        parser.setTagTable(4, tagTablePage4);
        parser.setTagTable(5, tagTablePage5);
        parser.setTagTable(6, tagTablePage6);
        parser.setTagTable(7, tagTablePage7);
        parser.setTagTable(8, tagTablePage8);
        parser.setTagTable(9, tagTablePage9);
        parser.setTagTable(10, tagTablePageA);
        parser.setAttrStartTable(0, attrStartTable);
        parser.setAttrValueTable(0, attrValueTable);
        return parser;
    }

    static {
        tagTablePage0 = new String[]{"Acceptance", "AddList", "AddNickList", "SName", "WV-CSP-Message", "ClientID", "Code", "ContactList", "ContentData", "ContentEncoding", "ContentSize", "ContentType", "DateTime", "Description", "DetailedResult", "EntityList", CollageParser.ATTR_Group, "GroupID", "GroupList", "InUse", "Logo", "MessageCount", "MessageID", "MessageURI", "MSISDN", "Name", "NickList", "NickName", "Poll", "Presence", "PresenceSubList", "PresenceValue", "Property", "Qualifier", "Recipient", "RemoveList", "RemoveNickList", "Result", "ScreenName", "Sender", "Session", "SessionDescriptor", "SessionID", "SessionType", "Status", "Transaction", "TransactionContent", "TransactionDescriptor", "TransactionID", "TransactionMode", "URL", "URLList", FlurryLogString.KEY_USER, "UserID", "UserList", "Validity", "Value"};
        tagTablePage1 = new String[]{"AllFunctions", "AllFunctionsRequest", "CancelInvite-Request", "CancelInviteUser-Request", "Capability", "CapabilityList", "CapabilityRequest", "ClientCapability-Request", "ClientCapability-Response", "DigestBytes", "DigestSchema", "Disconnect", "Functions", "GetSPInfo-Request", "GetSPInfo-Response", "InviteID", "InviteNote", "Invite-Request", "Invite-Response", "InviteType", "InviteUser-Request", "InviteUser-Response", "KeepAlive-Request", "KeepAliveTime", "Login-Request", "Login-Response", "Logout-Request", "Nonce", "Password", "Polling-Request", "ResponseNote", "SearchElement", "SearchFindings", "SearchID", "SearchIndex", "SearchLimit", "KeepAlive-Response", "SearchPairList", "Search-Request", "Search-Response", "SearchResult", "Service-Request", "Service-Response", "SessionCookie", "StopSearch-Request", "TimeToLive", "SearchString", "CompletionFlag", null, "ReceiveList", "VerifyID-Request", "Extended-Request", "Extended-Response", "AgreedCapabilityList", "Extended-Data", "OtherServer", "PresenceAttributeNSName", "SessionNSName", "TransactionNSName"};
        tagTablePage2 = new String[]{"ADDGM", "AttListFunc", "BLENT", "CAAUT", "CAINV", "CALI", "CCLI", "ContListFunc", "CREAG", "DALI", "DCLI", "DELGR", "FundamentalFeat", "FWMSG", "GALS", "GCLI", "GETGM", "GETGP", "GETLM", "GETM", "GETPR", "GETSPI", "GETWL", "GLBLU", "GRCHN", "GroupAuthFunc", "GroupFeat", "GroupMgmtFunc", "GroupUseFunc", "IMAuthFunc", "IMFeat", "IMReceiveFunc", "IMSendFunc", "INVIT", "InviteFunc", "MBRAC", "MCLS", "MDELIV", "NEWM", "NOTIF", "PresenceAuthFunc", "PresenceDeliverFunc", "PresenceFeat", "REACT", "REJCM", "REJEC", "RMVGM", "SearchFunc", "ServiceFunc", "SETD", "SETGP", "SRCH", "STSRC", "SUBGCN", "UPDPR", "WVCSPFeat", "MF", "MG", "MM"};
        tagTablePage3 = new String[]{"AcceptedCharset", "AcceptedContentLength", "AcceptedContentType", "AcceptedTransferEncoding", "AnyContent", "DefaultLanguage", "InitialDeliveryMethod", "MultiTrans", "ParserSize", "ServerPollMin", "SupportedBearer", "SupportedCIRMethod", "TCPAddress", "TCPPort", "UDPPort"};
        tagTablePage4 = new String[]{"CancelAuth-Request", "ContactListProperties", "CreateAttributeList-Request", "CreateList-Request", "DefaultAttributeList", "DefaultContactList", "DefaultList", "DeleteAttributeList-Request", "DeleteList-Request", "GetAttributeList-Request", "GetAttributeList-Response", "GetList-Request", "GetList-Response", "GetPresence-Request", "GetPresence-Response", "GetWatcherList-Request", "GetWatcherList-Response", "ListManage-Request", "ListManage-Response", "UnsubscribePresence-Request", "PresenceAuth-Request", "PresenceAuth-User", "PresenceNotification-Request", "UpdatePresence-Request", "SubscribePresence-Request", "Auto-Subscribe", "GetReactiveAuthStatus-Request", "GetReactiveAuthStatus-Response"};
        tagTablePage5 = new String[]{"Accuracy", "Address", "AddrPref", "Alias", "Altitude", "Building", "Caddr", "City", "ClientInfo", "ClientProducer", "ClientType", "ClientVersion", "CommC", "CommCap", "ContactInfo", "ContainedvCard", OfflineADParser.ATTR_Country, "Crossing1", "Crossing2", "DevManufacturer", "DirectContent", "FreeTextLocation", "GeoLocation", "Language", "Latitude", "Longitude", "Model", "NamedArea", "OnlineStatus", "PLMN", "PrefC", "PreferredContacts", "PreferredLanguage", "PreferredContent", "PreferredvCard", "Registration", "StatusContent", "StatusMood", "StatusText", "Street", "TimeZone", "UserAvailability", "Cap", "Cname", "Contact", "Cpriority", "Cstatus", "Note", "Zone", null, "Inf_link", "InfoLink", "Link", "Text"};
        tagTablePage6 = new String[]{"BlockList", "BlockEntity-Request", "DeliveryMethod", "DeliveryReport", "DeliveryReport-Request", "ForwardMessage-Request", "GetBlockedList-Request", "GetBlockedList-Response", "GetMessageList-Request", "GetMessageList-Response", "GetMessage-Request", "GetMessage-Response", "GrantList", "MessageDelivered", "MessageInfo", "MessageNotification", "NewMessage", "RejectMessage-Request", "SendMessage-Request", "SendMessage-Response", "SetDeliveryMethod-Request", "DeliveryTime"};
        tagTablePage7 = new String[]{"AddGroupMembers-Request", "Admin", "CreateGroup-Request", "DeleteGroup-Request", "GetGroupMembers-Request", "GetGroupMembers-Response", "GetGroupProps-Request", "GetGroupProps-Response", "GroupChangeNotice", "GroupProperties", "Joined", "JoinedRequest", "JoinGroup-Request", "JoinGroup-Response", "LeaveGroup-Request", "LeaveGroup-Response", CollageParser.ATTR_Left, "MemberAccess-Request", "Mod", "OwnProperties", "RejectList-Request", "RejectList-Response", "RemoveGroupMembers-Request", "SetGroupProps-Request", "SubscribeGroupNotice-Request", "SubscribeGroupNotice-Response", "Users", "WelcomeNote", "JoinGroup", "SubscribeNotification", "SubscribeType", "GetJoinedUsers-Request", "GetJoinedUsers-Response", "AdminMapList", "AdminMapping", "Mapping", "ModMapping", "UserMapList", "UserMapping"};
        tagTablePage8 = new String[]{"MP", "GETAUT", "GETJU", "VRID", "VerifyIDFunc"};
        tagTablePage9 = new String[]{"CIR", "Domain", "ExtBlock", "HistoryPeriod", "IDList", "MaxWatcherList", "ReactiveAuthState", "ReactiveAuthStatus", "ReactiveAuthStatusList", "Watcher", "WatcherStatus"};
        tagTablePageA = new String[]{"WV-CSP-NSDiscovery-Request", "WV-CSP-NSDiscovery-Response", "VersionList"};
        attrStartTable = new String[]{"xmlns=http://www.wireless-village.org/CSP", "xmlns=http://www.wireless-village.org/PA", "xmlns=http://www.wireless-village.org/TRC", "xmlns=http://www.openmobilealliance.org/DTD/WV-CSP", "xmlns=http://www.openmobilealliance.org/DTD/WV-PA", "xmlns=http://www.openmobilealliance.org/DTD/WV-TRC"};
        String[] strArr = new String[SoapEnvelope.VER12];
        strArr[0] = "AccessType";
        strArr[1] = "ActiveUsers";
        strArr[2] = "Admin";
        strArr[3] = "application/";
        strArr[4] = "application/vnd.wap.mms-message";
        strArr[5] = "application/x-sms";
        strArr[6] = "AutoJoin";
        strArr[7] = "BASE64";
        strArr[8] = "Closed";
        strArr[9] = "Default";
        strArr[10] = "DisplayName";
        strArr[11] = "F";
        strArr[12] = "G";
        strArr[13] = "GR";
        strArr[14] = "http://";
        strArr[15] = "https://";
        strArr[16] = "image/";
        strArr[17] = "Inband";
        strArr[18] = "IM";
        strArr[19] = "MaxActiveUsers";
        strArr[20] = "Mod";
        strArr[21] = "Name";
        strArr[22] = "None";
        strArr[23] = "N";
        strArr[24] = "Open";
        strArr[25] = "Outband";
        strArr[26] = "PR";
        strArr[27] = "Private";
        strArr[28] = "PrivateMessaging";
        strArr[29] = "PrivilegeLevel";
        strArr[30] = "Public";
        strArr[31] = "P";
        strArr[32] = "Request";
        strArr[33] = "Response";
        strArr[34] = "Restricted";
        strArr[35] = "ScreenName";
        strArr[36] = "Searchable";
        strArr[37] = "S";
        strArr[38] = "SC";
        strArr[39] = "text/";
        strArr[40] = "text/plain";
        strArr[41] = "text/x-vCalendar";
        strArr[42] = "text/x-vCard";
        strArr[43] = "Topic";
        strArr[44] = "T";
        strArr[45] = OfflineADParser.ATTR_Type;
        strArr[46] = "U";
        strArr[47] = "US";
        strArr[48] = "www.wireless-village.org";
        strArr[49] = "AutoDelete";
        strArr[50] = "GM";
        strArr[51] = "Validity";
        strArr[52] = "ShowID";
        strArr[53] = "GRANTED";
        strArr[54] = "PENDING";
        strArr[55] = null;
        strArr[56] = null;
        strArr[57] = null;
        strArr[58] = null;
        strArr[59] = null;
        strArr[60] = null;
        strArr[61] = "GROUP_ID";
        strArr[62] = "GROUP_NAME";
        strArr[63] = "GROUP_TOPIC";
        strArr[64] = "GROUP_USER_ID_JOINED";
        strArr[65] = "GROUP_USER_ID_OWNER";
        strArr[66] = "HTTP";
        strArr[67] = "SMS";
        strArr[68] = "STCP";
        strArr[69] = "SUDP";
        strArr[70] = "USER_ALIAS";
        strArr[71] = "USER_EMAIL_ADDRESS";
        strArr[72] = "USER_FIRST_NAME";
        strArr[73] = "USER_ID";
        strArr[74] = "USER_LAST_NAME";
        strArr[75] = "USER_MOBILE_NUMBER";
        strArr[76] = "USER_ONLINE_STATUS";
        strArr[77] = "WAPSMS";
        strArr[78] = "WAPUDP";
        strArr[79] = "WSP";
        strArr[80] = "GROUP_USER_ID_AUTOJOIN";
        strArr[81] = null;
        strArr[82] = null;
        strArr[83] = null;
        strArr[84] = null;
        strArr[85] = null;
        strArr[86] = null;
        strArr[87] = null;
        strArr[88] = null;
        strArr[89] = null;
        strArr[90] = null;
        strArr[91] = "ANGRY";
        strArr[92] = "ANXIOUS";
        strArr[93] = "ASHAMED";
        strArr[94] = "AUDIO_CALL";
        strArr[95] = "AVAILABLE";
        strArr[96] = "BORED";
        strArr[97] = "CALL";
        strArr[98] = "CLI";
        strArr[99] = "COMPUTER";
        strArr[100] = "DISCREET";
        strArr[ControllerState.PLAY_PHOTO] = "EMAIL";
        strArr[ControllerState.NO_PLAY_ITEM] = "EXCITED";
        strArr[ControllerState.PLAY_COUNT_STATE] = "HAPPY";
        strArr[104] = "IM";
        strArr[105] = "IM_OFFLINE";
        strArr[106] = "IM_ONLINE";
        strArr[107] = "IN_LOVE";
        strArr[108] = "INVINCIBLE";
        strArr[109] = "JEALOUS";
        strArr[POP3.DEFAULT_PORT] = "MMS";
        strArr[111] = "MOBILE_PHONE";
        strArr[112] = "NOT_AVAILABLE";
        strArr[113] = "OTHER";
        strArr[114] = "PDA";
        strArr[DNSConstants.RESPONSE_MAX_WAIT_INTERVAL] = "SAD";
        strArr[116] = "SLEEPY";
        strArr[117] = "SMS";
        strArr[118] = "VIDEO_CALL";
        strArr[NNTP.DEFAULT_PORT] = "VIDEO_STREAM";
        attrValueTable = strArr;
    }
}
