package com.hiti.utility.Install;

public enum ZIP_AND_COPY_INSTALLER_ERROR {
    NON,
    ERROR_UNZIP,
    ERROR_COPY_FILE,
    ERROR_COPY_FILE_CONFIG_XML_NOT_FOUND_PATH,
    ERROR_COPY_FILE_CONFIG_XML_PARSE_FAIL,
    ERROR_COPY_FILE_RESPONSE_BACK_FAIL,
    ERROR_COPY_FILE_RESPONSE_SERVER_REJECT,
    ERROR_USER_INVALID
}
