package com.hiti.multiphoto;

public enum WEB_UPLOAD_ERROR {
    UPLOAD_SUCCESS,
    UPLOAD_INTERNET_FAIL,
    UPLOAD_FILE_NOT_FOUND,
    UPLOAD_VERIFY_UNVALID,
    UPLOAD_CANCEL,
    UPLOAD_PHOTO_REPEAT_ON_SERVER,
    TIME_OUT
}
